# Generated by Django 5.1.6 on 2025-03-26 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filedactuapp", "0002_rename_content_messages_contents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="reponse_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="filedactuapp.messages",
            ),
        ),
    ]
